### ISSUE TITLE
Doesn't function.

### ISSUE THREAD

**Issue by JillSwift** [Ivan0xFF/BetterSignsAndFrames#1]
Mod appears to load, however:

Doesn't show up in ModMenu
Neither Shift-Use or Shift-Attack bring up the sign editor.

Attaching log.
[SignEditLog.txt](https://github.com/Ivan0xFF/signEditor/files/4665863/SignEditLog.txt)

**Comment by Ivan0xFF** [comment]
@JillSwift thanks for the bug report! Are you using this mod on a server, or client? I've only tested it on the server side.

**Comment by JillSwift** [comment]
Client (single player).

**Comment by Ivan0xFF** [comment]
I haven't tested single player, but it should work. I'll give it a try later and try to fix it up.

**Comment by Ivan0xFF** [comment]
It should now work on Single Player as of 0.5.1
