### ISSUE TITLE
Dye 'passthrough' signs

### ISSUE THREAD

**Issue by MeeniMc** [Ivan0xFF/BetterSignsAndFrames#13]
When using a Dye item to color the text of a sign, the Dye 'passthrough' to the item behind it. It the item is a sign, it will also be dyed at the same time. Imagine the following setup (with player facing to the right, and the signs installed onto one another): 

```
Player    S1    S2     S3     Chest
```

If the player clicks S1 with a dye, both S1 and S2 will get colored;

If the player clicks S2 with a dye, both S2 and S3 will get colored;

If the player clicks S3 with a dye, S3 will be colored, and the Chest will open. 

MC1.17 / BS&F 0.7.1

**Comment by Ivan0xFF** [comment]
That's hilarious. I noticed that when dying/glowing a sign it will still open the chest, but had not noticed that it also 'pass-through' dyes.

Shouldn't be too hard to fix

**Comment by Ivan0xFF** [comment]
Fixed in 0.8.1!
