### ISSUE TITLE
Tag files with "fabric" on CurseForge

### ISSUE THREAD

**Issue by koelle25** [Ivan0xFF/BetterSignsAndFrames#17]
Hi there,

thank you for this mod! I think some of its features are a must-have (e.g. editing signs).

Unfortunately I have a small problem. I recently started or wanted to start using the CurseForge app to handle my (by now) relatively long mod list. But it is currently not possible to install your mod in the CurseForge app.

I am almost certain this is because the mod files are missing the `fabric` tag CurseForge. Could you add it there?

Thanks in advance and have a nice day,
Kölle

**Comment by Ivan0xFF** [comment]
Fixed
