### ISSUE TITLE
Editing a Sign Results Removes All Text Previously on the Sign

### ISSUE THREAD

**Issue by IAmSneak** [Ivan0xFF/BetterSignsAndFrames#2]
If you shift right click to edit a sign it removes the text on the sign meaning you need to rewrite everything on the sign.

This is on a 1.16.1 server with the mod installed on the server.

**Comment by Ivan0xFF** [comment]
Thanks for the bug report! It seems like some behavior has changed in the client that affects this. It might require a client-side mod to fix.
I'm still looking into it!

**Comment by Ivan0xFF** [comment]
Issue is fixed with the latest release (0.6.1). However, you need to install the mod on both the client and server to fix this issue.
