### ISSUE TITLE
Clicking on a chest through an itemframe leaves the chest open

### ISSUE THREAD

**Issue by MeeniMc** [Ivan0xFF/BetterSignsAndFrames#3]
When one clicks on a chest through an item frame, the chest 'open' animation does not happen.

On the integrated server (single player mode), the chest remains closed at all time during and after the interaction.

On an external server (dedicated server), the chest 'open' animation is triggered when 'leaving' the chest, and the  chest remains visibly 'open' forever, although no player is interacting with it anymore.

**Comment by MeeniMc** [comment]
Issue is resolved on integrated server

**Comment by Ivan0xFF** [comment]
I have not been able to reproduce it lately either. Closing for now
