### ISSUE TITLE
1.16.3 crash/update

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Ivan0xFF/BetterSignsAndFrames#4]
Looks like this needs a 1.16.3 update. 
When shift-clicking a sign on a shulker box my game crashes. 
Tested with
- better-signs-and-frames-mc-1.16.1-0.6.1
- fabric-api-0.24.1+build.412-1.16
- notenoughcrashes-2.1.4+1.16.2

[crash.txt](https://pastebin.com/We2bNKKt)
[latest.log](https://pastebin.com/dM6Gs8eu)

**Comment by Ivan0xFF** [comment]
Fixed by #7
