### ISSUE TITLE
Flan compability

### ISSUE THREAD

**Issue by CodedSakura** [Ivan0xFF/BetterSignsAndFrames#6]
It seems this mod allows editing signs and opening chests through item frames within [Flan](https://github.com/Flemmli97/Flan) claims. I would like to either see some integration for Flan permissions, or some other fix, since this is (in my opinion) quite a major problem

**Comment by Ivan0xFF** [comment]
I'd welcome an MR with this functionality, but I don't personally use Flan.

**Comment by Soham52** [comment]
So will you not fix this?

**Comment by Ivan0xFF** [comment]
I might, but it's not a priority for me.

**Comment by Soham52** [comment]
Oh ;-;

**Comment by elhertz** [comment]
+1

**Comment by Ivan0xFF** [comment]
This is now fixed in 0.8.5
