### ISSUE TITLE
[Bug/Compat] Can't edit wall signs

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Ivan0xFF/BetterSignsAndFrames#9]
I can edit standing signs but not wall signs when I right-click them. 
Using `better-signs-and-frames-mc-1.16.5-0.7.0` on fabric 1.16.5. 

Can anyone confirm this issue? It might be a conflict, but that'd be a pretty weird conflict.

**Comment by Ivan0xFF** [comment]
I have not been able to reproduce this. If you can figure out what mod is conflicting, I can take another look at it.
